apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: meterstream
  labels:
    app: processor
spec:
  selector:
    app: processor
  ports:
    - name: http
      port: 8001
      targetPort: http
  type: ClusterIP
