apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  type: ClusterIP
  selector:
    app: ingestion
  ports:
    - port: 8000
      targetPort: 8000
      name: http
