apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dev
  namespace: meterstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dev
  template:
    metadata:
      labels:
        app: grafana-dev
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.2.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

            - name: GF_AUTH_PROXY_ENABLED
              value: "false"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"

            - name: GF_USERS_DEFAULT_THEME
              value: light
            - name: GF_DEFAULT_LANGUAGE
              value: sv-SE

            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-init
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN

          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-dev-storage
