# Grafana-dev persistenta GUI-grafer.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dev-storage
  namespace: meterstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
